version: "2.1"
services:
  zoo:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo
    ports:
      - "2181:2181"
    container_name: zookeeper

  # kafka version: 1.1.0
  # scala version: 2.12
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zoo
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
      - zoo
    container_name: kafka
  jobmanager:
    image: flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    links:
      - "zoo:zoo"
      - "kafka:kafka"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    container_name: flinkjob

  taskmanager:
    image: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
      - "zoo:zoo"
      - "kafka:kafka"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    container_name: flinktask
